export const TOGGLE_SETTINGS_MODAL = "TOGGLE_SETTINGS_MODAL";
export const TOGGLE_DELETE_MODAL = "TOGGLE_DELETE_MODAL";
export const TOGGLE_FORM_MODAL = "TOGGLE_FORM_MODAL";
export const UPDATE_MONEY_INFORMATION = "UPDATE_MONEY_INFORMATION";
export const UPDATE_CURRENT_PRICE_FOR_ITEMS = "UPDATE_CURRENT_PRICE_FOR_ITEMS";
export const UPDATE_TARGETED_ITEM = "UPDATE_TARGETED_ITEM";
export const UPDATE_ITEM_INFORMATION = "UPDATE_ITEM_INFORMATION";
export const DELETE_ITEM = "DELETE_ITEM";