export const TOGGLE_SETTINGS_MODAL = "TOGGLE_SETTINGS_MODAL";
export const UPDATE_MONEY_INFORMATION = "UPDATE_MONEY_INFORMATION";
export const UPDATE_CURRENT_PRICE_FOR_ITEMS = "UPDATE_CURRENT_PRICE_FOR_ITEMS";